import "../styles/main.sass";
import type { AppProps } from "next/app";
import Head from "next/head";
import { MantineProvider } from '@mantine/core';


export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Cool Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokedex.png" />
      </Head>
      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        theme={{
          /** Put your mantine theme override here */
          colorScheme: 'light',
        }}
      >
        <Component {...pageProps} />

      </MantineProvider>
      
    </>
  );
}
