import "../styles/main.sass";
import type { AppProps } from "next/app";
import Head from "next/head";
import { MantineProvider } from "@mantine/core";
import IndexContextProvider from "../contexts/indexContext";
import BottomNav from "../components/BottomNav/BottomNav";
import PokemonSingleContextProvider from "../contexts/pokemonSingleContext";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Cool Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokedex.png" />
      </Head>
      <BottomNav></BottomNav>
      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        theme={{
          /** Put your mantine theme override here */
          colorScheme: "light",
        }}
      >
        <IndexContextProvider>
          <PokemonSingleContextProvider>
            <Component {...pageProps} />
          </PokemonSingleContextProvider>
        </IndexContextProvider>
      </MantineProvider>
    </>
  );
}
